export const UPDATE_REGISTRATION_FORM = "UPDATE_REGISTRATION_FORM";
export const UPDATE_ACCOUNT_FORM = "UPDATE_ACCOUNT_FORM";
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";

export const UDPATE_CURRENT_ACCOUNT_USER = "UDPATE_CURRENT_ACCOUNT_USER";
export const UDPATE_ACCOUNT_USER_SET = "UDPATE_ACCOUNT_USER_SET";

export const UPDATE_PROFILE_FORM = "UPDATE_PROFILE_FORM";

export const ADD_VARIATION_PRODUCT_FORM = "ADD_VARIATION_PRODUCT_FORM";
export const DELETE_VARIATION_PRODUCT_FORM = "DELETE_VARIATION_PRODUCT_FORM";
export const UPDATE_PRODUCT_FORM = "UPDATE_PRODUCT_FORM";
export const ADD_IMAGE_PRODUCT_FORM = "ADD_IMAGE_PRODUCT_FORM";

export const UDPATE_PANEL = "UDPATE_PANEL";
export const TOGGLE_NAV = "TOGGLE_NAV";
