export const UPDATE_REGISTRATION_FORM = "UPDATE_REGISTRATION_FORM";
export const UPDATE_ACCOUNT_FORM = "UPDATE_ACCOUNT_FORM";
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";
export const UPDATE_ACCOUNT_USER_SET = "UPDATE_ACCOUNT_USER_SET";
